### ISSUE TITLE
Add pagination to projects page

### ISSUE THREAD

**Issue by Knochenmark** [Knochenmark/gatsby-starter-level-2#137]
- [x] Add pagination similar to blog page
- [x] Add a few more example/test projects to increase page count

**Comment by alammoiz** [comment]
I would love to do this task, Please assign it to me @Knochenmark

**Comment by Knochenmark** [comment]
@alammoiz assigned you. I think the styling of the pagination is currently slightly broken, maybe due to some version updates. Don't bother too much, as long as it looks like in the blog page you'll be fine.

**Comment by alammoiz** [comment]
> @alammoiz assigned you. I think the styling of the pagination is currently slightly broken, maybe due to some version updates. Don't bother too much, as long as it looks like in the blog page you'll be fine.

Here is my PR 
https://github.com/Knochenmark/gatsby-starter-level-2/pull/138
